manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: miramesh-zephyr
      url-base: https://github.com/LumenRadio
  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: ncs
      revision: v2.5.1
      import: true
    - name: miramesh-zephyr
      remote: miramesh-zephyr
      repo-path: miramesh-zephyr
      path: modules/miramesh-zephyr
      revision: miramesh-2.10.0-ncs-v2.5.1
  self:
    path: miramesh-network-example
